[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "housing_predictor"
version = "0.0.1"
description = "Predicting Seattle home prices using machine learning to support first-time buyers and inform real estate decisions."
authors = [
  { name = "Jaylen Carrillo" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = "~=3.10.0"


[tool.ruff]
line-length = 99
src = ["housing_predictor"]
include = ["pyproject.toml", "housing_predictor/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["housing_predictor"]
force-sort-within-sections = true

